version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp-server
    container_name: myapp-node-server
    command: npm run server
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - mongo
    env_file: .env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  mongo:
    image: mongo
    command: mongod --quiet --logpath /dev/null 
    volumes:
      - data-volume:/data/db
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    networks:
      - app-network
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: myapp-client
    container_name: myapp-react-client
    command: yarn start
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local
